export interface StateData {
  name: string;
  abbr: string;
  filingFee: number;
  processingTime: string;
  expeditedFee: number | null;
  expeditedTime: string | null;
  annualReportFee: number | null;
  annualReportDue: string;
  stateTax: string;
  franchiseTax: number | null;
  franchiseTaxNote: string;
  namingRequirements: string[];
  publicationRequired: boolean;
  publicationNote: string;
  registeredAgentRequired: boolean;
  filingOffice: string;
  filingUrl: string;
  einRequired: boolean;
  operatingAgreementRequired: boolean;
  operatingAgreementNote: string;
  keyFacts: string[];
  warnings: string[];
}

export const LLC_STATES: Record<string, StateData> = {
  AL: {
    name: "Alabama", abbr: "AL", filingFee: 200, processingTime: "5–7 business days",
    expeditedFee: null, expeditedTime: null,
    annualReportFee: 0, annualReportDue: "Annual report + $100 privilege tax, April 15",
    stateTax: "5%", franchiseTax: 100, franchiseTaxNote: "Minimum Business Privilege Tax $100/year",
    namingRequirements: ["Must include 'LLC', 'L.L.C.', 'Limited Liability Company'", "Cannot include 'Bank', 'Insurance' without approval"],
    publicationRequired: false, publicationNote: "",
    registeredAgentRequired: true, filingOffice: "Alabama Secretary of State",
    filingUrl: "https://sos.alabama.gov/business-services/llcs",
    einRequired: true, operatingAgreementRequired: false,
    operatingAgreementNote: "Not legally required but strongly recommended",
    keyFacts: ["Online filing available", "$100 minimum privilege tax due annually", "Domestic LLC formation is $200"],
    warnings: ["$100 annual privilege tax applies even to inactive LLCs"]
  },
  AK: {
    name: "Alaska", abbr: "AK", filingFee: 250, processingTime: "10–15 business days",
    expeditedFee: null, expeditedTime: null,
    annualReportFee: 100, annualReportDue: "Biennial report, January 2",
    stateTax: "No state income tax", franchiseTax: null, franchiseTaxNote: "",
    namingRequirements: ["Must include 'LLC', 'L.L.C.', or 'Limited Liability Company'"],
    publicationRequired: false, publicationNote: "",
    registeredAgentRequired: true, filingOffice: "Alaska Division of Corporations",
    filingUrl: "https://www.commerce.alaska.gov/web/cbpl/corporations",
    einRequired: true, operatingAgreementRequired: false,
    operatingAgreementNote: "Not required but highly recommended",
    keyFacts: ["No state personal income tax", "Biennial report required ($100)", "Remote filing available"],
    warnings: []
  },
  AZ: {
    name: "Arizona", abbr: "AZ", filingFee: 50, processingTime: "14–16 business days",
    expeditedFee: 35, expeditedTime: "3–5 business days",
    annualReportFee: 0, annualReportDue: "No annual report required",
    stateTax: "2.5% flat", franchiseTax: null, franchiseTaxNote: "",
    namingRequirements: ["Must include 'LLC', 'L.L.C.', or 'Limited Liability Company'", "Cannot use 'Association', 'Company', 'Corporation', 'Club' alone"],
    publicationRequired: true, publicationNote: "Must publish notice in a county newspaper for 3 consecutive weeks within 60 days of filing (Maricopa & Pima counties exempt)",
    registeredAgentRequired: true, filingOffice: "Arizona Corporation Commission",
    filingUrl: "https://ecorp.azcc.gov",
    einRequired: true, operatingAgreementRequired: false,
    operatingAgreementNote: "Not required but strongly recommended",
    keyFacts: ["Very low $50 filing fee", "No annual report or renewal fee", "2.5% flat income tax rate (very competitive)"],
    warnings: ["PUBLICATION REQUIRED outside Maricopa/Pima — costs $50–$200 extra", "Must complete within 60 days of formation"]
  },
  AR: {
    name: "Arkansas", abbr: "AR", filingFee: 50, processingTime: "3–5 business days",
    expeditedFee: 300, expeditedTime: "Same day",
    annualReportFee: 150, annualReportDue: "Annual Franchise Tax Report, May 1",
    stateTax: "4.4%", franchiseTax: 150, franchiseTaxNote: "$150 minimum franchise tax annually",
    namingRequirements: ["Must include 'LLC', 'L.L.C.', 'Limited Liability Co.', or 'Limited Liability Company'"],
    publicationRequired: false, publicationNote: "",
    registeredAgentRequired: true, filingOffice: "Arkansas Secretary of State",
    filingUrl: "https://www.sos.arkansas.gov/corps/search_all.php",
    einRequired: true, operatingAgreementRequired: false,
    operatingAgreementNote: "Recommended but not required",
    keyFacts: ["Low $50 formation fee", "Online filing available", "$150 minimum franchise tax per year"],
    warnings: ["Annual franchise tax of $150 minimum even for inactive LLCs"]
  },
  CA: {
    name: "California", abbr: "CA", filingFee: 70, processingTime: "3–5 business days (online)",
    expeditedFee: null, expeditedTime: null,
    annualReportFee: 20, annualReportDue: "Biennial Statement of Information, $20, within 90 days of formation then every 2 years",
    stateTax: "1–13.3%", franchiseTax: 800, franchiseTaxNote: "$800 minimum annual franchise tax — waived first year (2021+ law)",
    namingRequirements: ["Must include 'LLC', 'L.L.C.', or 'Limited Liability Company'", "Cannot use 'Bank', 'Trust', 'Trustee', 'Insurance' without approval"],
    publicationRequired: false, publicationNote: "",
    registeredAgentRequired: true, filingOffice: "California Secretary of State",
    filingUrl: "https://www.sos.ca.gov/business-programs/business-entities",
    einRequired: true, operatingAgreementRequired: false,
    operatingAgreementNote: "Not required but California Revised Uniform LLC Act strongly benefits from written agreement",
    keyFacts: ["First-year $800 franchise tax WAIVED for LLCs formed 2021 onward (until 2024 — check current law)", "Biennial Statement of Information: $20", "LLCs with $250K+ CA gross revenue pay additional fee"],
    warnings: ["$800 MINIMUM annual franchise tax — expensive for inactive LLCs", "Additional LLC fee for high-revenue companies: $900–$11,790/year", "California has highest LLC taxes in the country"]
  },
  CO: {
    name: "Colorado", abbr: "CO", filingFee: 50, processingTime: "Immediate (online)",
    expeditedFee: null, expeditedTime: null,
    annualReportFee: 10, annualReportDue: "Periodic Report, $10, annually by end of anniversary month",
    stateTax: "4.4% flat", franchiseTax: null, franchiseTaxNote: "",
    namingRequirements: ["Must include 'LLC', 'L.L.C.', 'Limited Liability Company', or 'Ltd. Liability Co.'"],
    publicationRequired: false, publicationNote: "",
    registeredAgentRequired: true, filingOffice: "Colorado Secretary of State",
    filingUrl: "https://www.sos.state.co.us/biz/BusinessHome.do",
    einRequired: true, operatingAgreementRequired: false,
    operatingAgreementNote: "Recommended but not required",
    keyFacts: ["Fast online formation — often immediate", "Low $10 annual report fee", "4.4% flat income tax"],
    warnings: []
  },
  CT: {
    name: "Connecticut", abbr: "CT", filingFee: 120, processingTime: "3–5 business days",
    expeditedFee: 50, expeditedTime: "24 hours",
    annualReportFee: 80, annualReportDue: "Annual Report, $80, by anniversary date",
    stateTax: "3–6.99%", franchiseTax: null, franchiseTaxNote: "",
    namingRequirements: ["Must include 'LLC', 'L.L.C.', or 'Limited Liability Company'"],
    publicationRequired: false, publicationNote: "",
    registeredAgentRequired: true, filingOffice: "Connecticut Secretary of State",
    filingUrl: "https://business.ct.gov",
    einRequired: true, operatingAgreementRequired: false,
    operatingAgreementNote: "Recommended but not required",
    keyFacts: ["Online filing available", "$80 annual report fee", "Business Entity Tax (BET) of $250 per 2 years for some entities"],
    warnings: []
  },
  DE: {
    name: "Delaware", abbr: "DE", filingFee: 90, processingTime: "3–5 business days",
    expeditedFee: 50, expeditedTime: "24 hours",
    annualReportFee: 300, annualReportDue: "Annual Franchise Tax, $300 minimum, June 1",
    stateTax: "No state income tax on out-of-state activity", franchiseTax: 300, franchiseTaxNote: "$300 minimum annual LLC franchise tax",
    namingRequirements: ["Must include 'LLC', 'L.L.C.', or 'Limited Liability Company'"],
    publicationRequired: false, publicationNote: "",
    registeredAgentRequired: true, filingOffice: "Delaware Division of Corporations",
    filingUrl: "https://corp.delaware.gov",
    einRequired: true, operatingAgreementRequired: false,
    operatingAgreementNote: "Not required but strongly recommended — Delaware has most flexible LLC law",
    keyFacts: ["Most popular state for VC-backed startups", "Strong legal precedent protecting business owners", "Chancery Court for business disputes (no jury)", "No state income tax on business conducted outside DE"],
    warnings: ["$300 minimum franchise tax annually", "If you live in another state, you'll need to foreign qualify in your home state — adds cost", "Best for VC funding — otherwise form in your home state"]
  },
  FL: {
    name: "Florida", abbr: "FL", filingFee: 125, processingTime: "3–5 business days (online)",
    expeditedFee: null, expeditedTime: null,
    annualReportFee: 138, annualReportDue: "Annual Report, $138.75, by May 1",
    stateTax: "No state income tax", franchiseTax: null, franchiseTaxNote: "",
    namingRequirements: ["Must include 'LLC', 'L.L.C.', or 'Limited Liability Company'", "Cannot use 'Corporation', 'Corp.', 'Incorporated', 'Inc.'"],
    publicationRequired: false, publicationNote: "",
    registeredAgentRequired: true, filingOffice: "Florida Division of Corporations",
    filingUrl: "https://dos.myflorida.com/sunbiz",
    einRequired: true, operatingAgreementRequired: false,
    operatingAgreementNote: "Not required but Florida Revised LLC Act benefits greatly from written agreement",
    keyFacts: ["No personal income tax", "Fast online filing via Sunbiz.org", "Annual report required by May 1"],
    warnings: ["Annual report late fee is $400 — file by May 1", "LLC gets dissolved if annual report not filed by 3rd Friday of September"]
  },
  GA: {
    name: "Georgia", abbr: "GA", filingFee: 100, processingTime: "5–7 business days",
    expeditedFee: 100, expeditedTime: "2 business days",
    annualReportFee: 50, annualReportDue: "Annual Registration, $50, by April 1",
    stateTax: "5.49% (flat rate phasing in)", franchiseTax: null, franchiseTaxNote: "",
    namingRequirements: ["Must include 'LLC', 'L.L.C.', or 'Limited Liability Company'"],
    publicationRequired: false, publicationNote: "",
    registeredAgentRequired: true, filingOffice: "Georgia Secretary of State",
    filingUrl: "https://sos.ga.gov/corporations",
    einRequired: true, operatingAgreementRequired: false,
    operatingAgreementNote: "Not required but recommended",
    keyFacts: ["Flat 5.49% income tax rate (decreasing)", "$50 annual registration fee", "Online filing via Georgia Corporations Division"],
    warnings: []
  },
  HI: {
    name: "Hawaii", abbr: "HI", filingFee: 50, processingTime: "3–5 business days",
    expeditedFee: 25, expeditedTime: "Same day",
    annualReportFee: 15, annualReportDue: "Annual Report, $15",
    stateTax: "1.4–11%", franchiseTax: null, franchiseTaxNote: "",
    namingRequirements: ["Must include 'LLC', 'L.L.C.', or 'Limited Liability Company'"],
    publicationRequired: false, publicationNote: "",
    registeredAgentRequired: true, filingOffice: "Hawaii Department of Commerce",
    filingUrl: "https://cca.hawaii.gov/breg",
    einRequired: true, operatingAgreementRequired: false,
    operatingAgreementNote: "Recommended but not required",
    keyFacts: ["Low filing fee ($50)", "General Excise Tax (GET) of 4% on gross revenue — not income", "GET applies to nearly all business activity"],
    warnings: ["General Excise Tax is unusual — applies to gross receipts, not profit", "High income tax rates up to 11%"]
  },
  ID: {
    name: "Idaho", abbr: "ID", filingFee: 100, processingTime: "3–5 business days",
    expeditedFee: null, expeditedTime: null,
    annualReportFee: 0, annualReportDue: "Annual Report, $0",
    stateTax: "5.8% flat", franchiseTax: null, franchiseTaxNote: "",
    namingRequirements: ["Must include 'LLC', 'L.L.C.', or 'Limited Liability Company'"],
    publicationRequired: false, publicationNote: "",
    registeredAgentRequired: true, filingOffice: "Idaho Secretary of State",
    filingUrl: "https://sos.idaho.gov/corp/llc.html",
    einRequired: true, operatingAgreementRequired: false,
    operatingAgreementNote: "Recommended but not required",
    keyFacts: ["Free annual report", "5.8% flat income tax", "Online filing available"],
    warnings: []
  },
  IL: {
    name: "Illinois", abbr: "IL", filingFee: 150, processingTime: "10 business days",
    expeditedFee: 100, expeditedTime: "24 hours",
    annualReportFee: 75, annualReportDue: "Annual Report, $75, before the first day of the LLC's anniversary month",
    stateTax: "4.95% flat", franchiseTax: null, franchiseTaxNote: "",
    namingRequirements: ["Must include 'LLC', 'L.L.C.', 'L.C.', 'LC', or 'Limited Liability Company'"],
    publicationRequired: false, publicationNote: "",
    registeredAgentRequired: true, filingOffice: "Illinois Secretary of State",
    filingUrl: "https://www.ilsos.gov/departments/business_services/home.html",
    einRequired: true, operatingAgreementRequired: false,
    operatingAgreementNote: "Recommended but not required",
    keyFacts: ["Online filing via Illinois Business Express", "$75 annual report", "4.95% flat income tax"],
    warnings: []
  },
  IN: {
    name: "Indiana", abbr: "IN", filingFee: 95, processingTime: "1–2 business days (online)",
    expeditedFee: null, expeditedTime: null,
    annualReportFee: 31, annualReportDue: "Business Entity Report, $31, every 2 years",
    stateTax: "3.05% flat (decreasing)", franchiseTax: null, franchiseTaxNote: "",
    namingRequirements: ["Must include 'LLC', 'L.L.C.', or 'Limited Liability Company'"],
    publicationRequired: false, publicationNote: "",
    registeredAgentRequired: true, filingOffice: "Indiana Secretary of State",
    filingUrl: "https://inbiz.in.gov",
    einRequired: true, operatingAgreementRequired: false,
    operatingAgreementNote: "Not required but recommended",
    keyFacts: ["Fast online filing", "One of lowest income tax rates in US (3.05%)", "Biennial report only $31"],
    warnings: []
  },
  IA: {
    name: "Iowa", abbr: "IA", filingFee: 50, processingTime: "5–7 business days",
    expeditedFee: null, expeditedTime: null,
    annualReportFee: 30, annualReportDue: "Biennial Report, $30",
    stateTax: "3.8%–5.7%", franchiseTax: null, franchiseTaxNote: "",
    namingRequirements: ["Must include 'LLC', 'L.L.C.', or 'Limited Liability Company'"],
    publicationRequired: false, publicationNote: "",
    registeredAgentRequired: true, filingOffice: "Iowa Secretary of State",
    filingUrl: "https://sos.iowa.gov/business/llc.html",
    einRequired: true, operatingAgreementRequired: false,
    operatingAgreementNote: "Recommended but not required",
    keyFacts: ["Low $50 formation fee", "Biennial report $30", "Online filing available"],
    warnings: []
  },
  KS: {
    name: "Kansas", abbr: "KS", filingFee: 160, processingTime: "3–5 business days",
    expeditedFee: null, expeditedTime: null,
    annualReportFee: 55, annualReportDue: "Annual Report, $55",
    stateTax: "3.1%–5.7%", franchiseTax: null, franchiseTaxNote: "",
    namingRequirements: ["Must include 'LLC', 'L.L.C.', or 'Limited Liability Company'"],
    publicationRequired: false, publicationNote: "",
    registeredAgentRequired: true, filingOffice: "Kansas Secretary of State",
    filingUrl: "https://www.sos.ks.gov/businesses/businesses.html",
    einRequired: true, operatingAgreementRequired: false,
    operatingAgreementNote: "Recommended but not required",
    keyFacts: ["Online filing via Kansas Business Center", "$55 annual report"],
    warnings: []
  },
  KY: {
    name: "Kentucky", abbr: "KY", filingFee: 40, processingTime: "3–5 business days",
    expeditedFee: null, expeditedTime: null,
    annualReportFee: 15, annualReportDue: "Annual Report, $15, by June 30",
    stateTax: "4% flat", franchiseTax: null, franchiseTaxNote: "",
    namingRequirements: ["Must include 'LLC', 'L.L.C.', or 'Limited Liability Company'"],
    publicationRequired: false, publicationNote: "",
    registeredAgentRequired: true, filingOffice: "Kentucky Secretary of State",
    filingUrl: "https://sos.ky.gov/bus/business-filings",
    einRequired: true, operatingAgreementRequired: false,
    operatingAgreementNote: "Recommended but not required",
    keyFacts: ["One of lowest formation fees ($40)", "Low annual report fee ($15)", "4% flat income tax"],
    warnings: []
  },
  LA: {
    name: "Louisiana", abbr: "LA", filingFee: 100, processingTime: "3–5 business days",
    expeditedFee: null, expeditedTime: null,
    annualReportFee: 30, annualReportDue: "Annual Report, $30, by anniversary",
    stateTax: "3%–6%", franchiseTax: null, franchiseTaxNote: "",
    namingRequirements: ["Must include 'LLC', 'L.L.C.', or 'Limited Liability Company'"],
    publicationRequired: false, publicationNote: "",
    registeredAgentRequired: true, filingOffice: "Louisiana Secretary of State",
    filingUrl: "https://www.sos.la.gov/BusinessServices",
    einRequired: true, operatingAgreementRequired: false,
    operatingAgreementNote: "Recommended but not required",
    keyFacts: ["Online filing via geauxBIZ", "$30 annual report"],
    warnings: []
  },
  ME: {
    name: "Maine", abbr: "ME", filingFee: 175, processingTime: "3–5 business days",
    expeditedFee: 100, expeditedTime: "Expedited available",
    annualReportFee: 85, annualReportDue: "Annual Report, $85, by June 1",
    stateTax: "5.8%–7.15%", franchiseTax: null, franchiseTaxNote: "",
    namingRequirements: ["Must include 'LLC', 'L.L.C.', or 'Limited Liability Company'"],
    publicationRequired: false, publicationNote: "",
    registeredAgentRequired: true, filingOffice: "Maine Secretary of State",
    filingUrl: "https://www.maine.gov/sos/cec/corp",
    einRequired: true, operatingAgreementRequired: false,
    operatingAgreementNote: "Recommended but not required",
    keyFacts: ["Online filing available", "$85 annual report"],
    warnings: []
  },
  MD: {
    name: "Maryland", abbr: "MD", filingFee: 100, processingTime: "7 business days",
    expeditedFee: 50, expeditedTime: "7 calendar days",
    annualReportFee: 300, annualReportDue: "Annual Report + Personal Property Return, $300 minimum, April 15",
    stateTax: "2%–5.75%", franchiseTax: null, franchiseTaxNote: "",
    namingRequirements: ["Must include 'LLC', 'L.L.C.', or 'Limited Liability Company'"],
    publicationRequired: false, publicationNote: "",
    registeredAgentRequired: true, filingOffice: "Maryland State Department of Assessments and Taxation",
    filingUrl: "https://dat.maryland.gov/businesses",
    einRequired: true, operatingAgreementRequired: false,
    operatingAgreementNote: "Recommended but not required",
    keyFacts: ["SDAT handles LLC filings", "$300 minimum annual report fee (high)"],
    warnings: ["$300 minimum annual report is one of the highest in the US"]
  },
  MA: {
    name: "Massachusetts", abbr: "MA", filingFee: 500, processingTime: "3–5 business days",
    expeditedFee: 20, expeditedTime: "Same day",
    annualReportFee: 500, annualReportDue: "Annual Report, $500, by anniversary",
    stateTax: "5% flat", franchiseTax: null, franchiseTaxNote: "",
    namingRequirements: ["Must include 'LLC', 'L.L.C.', or 'Limited Liability Company'"],
    publicationRequired: false, publicationNote: "",
    registeredAgentRequired: true, filingOffice: "Massachusetts Secretary of State",
    filingUrl: "https://corp.sec.state.ma.us",
    einRequired: true, operatingAgreementRequired: false,
    operatingAgreementNote: "Not required but strongly recommended",
    keyFacts: ["Online filing available", "Annual filing fee is same as formation ($500)"],
    warnings: ["$500 formation fee AND $500/year annual report — one of the most expensive states", "Consider New Hampshire next door — no income tax, lower fees"]
  },
  MI: {
    name: "Michigan", abbr: "MI", filingFee: 50, processingTime: "10–15 business days",
    expeditedFee: 50, expeditedTime: "24 hours",
    annualReportFee: 25, annualReportDue: "Annual Statement, $25, by February 15",
    stateTax: "4.25% flat", franchiseTax: null, franchiseTaxNote: "",
    namingRequirements: ["Must include 'LLC', 'L.L.C.', or 'Limited Liability Company'"],
    publicationRequired: false, publicationNote: "",
    registeredAgentRequired: true, filingOffice: "Michigan Department of Licensing and Regulatory Affairs",
    filingUrl: "https://www.michigan.gov/lara/bureau-list/bcs/corps",
    einRequired: true, operatingAgreementRequired: false,
    operatingAgreementNote: "Recommended but not required",
    keyFacts: ["Very low $50 formation fee", "Low $25 annual statement", "4.25% flat income tax"],
    warnings: ["Standard processing can be slow — use $50 expedite for 24-hour turnaround"]
  },
  MN: {
    name: "Minnesota", abbr: "MN", filingFee: 155, processingTime: "5–7 business days",
    expeditedFee: null, expeditedTime: null,
    annualReportFee: 0, annualReportDue: "Annual Renewal, $0, December 31",
    stateTax: "5.35%–9.85%", franchiseTax: null, franchiseTaxNote: "",
    namingRequirements: ["Must include 'LLC', 'L.L.C.', or 'Limited Liability Company'"],
    publicationRequired: false, publicationNote: "",
    registeredAgentRequired: true, filingOffice: "Minnesota Secretary of State",
    filingUrl: "https://www.sos.state.mn.us/business-liens/business-filings",
    einRequired: true, operatingAgreementRequired: false,
    operatingAgreementNote: "Recommended but not required",
    keyFacts: ["Free annual renewal", "Online filing available"],
    warnings: ["High income tax rates up to 9.85%"]
  },
  MS: {
    name: "Mississippi", abbr: "MS", filingFee: 50, processingTime: "3–5 business days",
    expeditedFee: null, expeditedTime: null,
    annualReportFee: 0, annualReportDue: "Annual Report, $0",
    stateTax: "4% flat (phasing in)", franchiseTax: null, franchiseTaxNote: "",
    namingRequirements: ["Must include 'LLC', 'L.L.C.', or 'Limited Liability Company'"],
    publicationRequired: false, publicationNote: "",
    registeredAgentRequired: true, filingOffice: "Mississippi Secretary of State",
    filingUrl: "https://www.sos.ms.gov/business-services-filing-forms",
    einRequired: true, operatingAgreementRequired: false,
    operatingAgreementNote: "Recommended but not required",
    keyFacts: ["Very low $50 formation fee", "Free annual report", "Phasing to 4% flat tax by 2026"],
    warnings: []
  },
  MO: {
    name: "Missouri", abbr: "MO", filingFee: 50, processingTime: "5–7 business days",
    expeditedFee: null, expeditedTime: null,
    annualReportFee: 0, annualReportDue: "No annual report required",
    stateTax: "4.7% flat", franchiseTax: null, franchiseTaxNote: "",
    namingRequirements: ["Must include 'LLC', 'L.L.C.', or 'Limited Liability Company'"],
    publicationRequired: false, publicationNote: "",
    registeredAgentRequired: true, filingOffice: "Missouri Secretary of State",
    filingUrl: "https://www.sos.mo.gov/business/corporations",
    einRequired: true, operatingAgreementRequired: false,
    operatingAgreementNote: "Recommended but not required",
    keyFacts: ["Very low $50 filing fee", "NO annual report required — standout benefit", "4.7% flat income tax"],
    warnings: []
  },
  MT: {
    name: "Montana", abbr: "MT", filingFee: 35, processingTime: "3–5 business days",
    expeditedFee: null, expeditedTime: null,
    annualReportFee: 15, annualReportDue: "Annual Report, $15, by April 15",
    stateTax: "5.9% flat", franchiseTax: null, franchiseTaxNote: "",
    namingRequirements: ["Must include 'LLC', 'L.L.C.', or 'Limited Liability Company'"],
    publicationRequired: false, publicationNote: "",
    registeredAgentRequired: true, filingOffice: "Montana Secretary of State",
    filingUrl: "https://sos.mt.gov/business",
    einRequired: true, operatingAgreementRequired: false,
    operatingAgreementNote: "Recommended but not required",
    keyFacts: ["Lowest formation fee in the US ($35)", "Low $15 annual report", "No sales tax"],
    warnings: []
  },
  NE: {
    name: "Nebraska", abbr: "NE", filingFee: 100, processingTime: "5–7 business days",
    expeditedFee: null, expeditedTime: null,
    annualReportFee: 13, annualReportDue: "Biennial Report, $13, April 1 every other year",
    stateTax: "2.46%–6.84%", franchiseTax: null, franchiseTaxNote: "",
    namingRequirements: ["Must include 'LLC', 'L.L.C.', or 'Limited Liability Company'"],
    publicationRequired: true, publicationNote: "Must publish notice of formation in a legal newspaper in the county for 3 consecutive weeks. Cost: $40–$100.",
    registeredAgentRequired: true, filingOffice: "Nebraska Secretary of State",
    filingUrl: "https://sos.nebraska.gov/business-services/corporation-forms",
    einRequired: true, operatingAgreementRequired: false,
    operatingAgreementNote: "Recommended but not required",
    keyFacts: ["Low biennial report fee ($13)", "Online filing available"],
    warnings: ["PUBLICATION REQUIRED — must publish in county newspaper for 3 consecutive weeks ($40–$100 additional cost)"]
  },
  NV: {
    name: "Nevada", abbr: "NV", filingFee: 75, processingTime: "1–3 business days (online)",
    expeditedFee: 125, expeditedTime: "24 hours",
    annualReportFee: 350, annualReportDue: "Annual List + Business License, $350 total, by anniversary month",
    stateTax: "No state income tax", franchiseTax: null, franchiseTaxNote: "",
    namingRequirements: ["Must include 'LLC', 'L.L.C.', or 'Limited Liability Company'"],
    publicationRequired: false, publicationNote: "",
    registeredAgentRequired: true, filingOffice: "Nevada Secretary of State",
    filingUrl: "https://esos.nv.gov",
    einRequired: true, operatingAgreementRequired: false,
    operatingAgreementNote: "Not required but strongly recommended",
    keyFacts: ["No state income tax", "Strong privacy protections (no public member listing)", "Good asset protection laws"],
    warnings: ["$350 annual fee (Annual List $150 + Business License $200) — higher than most", "If you live outside Nevada, you'll need to foreign qualify in your home state"]
  },
  NH: {
    name: "New Hampshire", abbr: "NH", filingFee: 100, processingTime: "5–7 business days",
    expeditedFee: null, expeditedTime: null,
    annualReportFee: 100, annualReportDue: "Annual Report, $100, by April 1",
    stateTax: "No income tax on wages (5% on interest/dividends phasing out)", franchiseTax: null, franchiseTaxNote: "",
    namingRequirements: ["Must include 'LLC', 'L.L.C.', or 'Limited Liability Company'"],
    publicationRequired: false, publicationNote: "",
    registeredAgentRequired: true, filingOffice: "New Hampshire Secretary of State",
    filingUrl: "https://www.sos.nh.gov/corporations",
    einRequired: true, operatingAgreementRequired: false,
    operatingAgreementNote: "Recommended but not required",
    keyFacts: ["No income tax on wages", "Interest/dividends tax phasing out completely by 2027", "Online filing available"],
    warnings: []
  },
  NJ: {
    name: "New Jersey", abbr: "NJ", filingFee: 125, processingTime: "1–2 business days (online)",
    expeditedFee: null, expeditedTime: null,
    annualReportFee: 75, annualReportDue: "Annual Report, $75, by anniversary",
    stateTax: "1.4%–10.75%", franchiseTax: null, franchiseTaxNote: "",
    namingRequirements: ["Must include 'LLC', 'L.L.C.', or 'Limited Liability Company'"],
    publicationRequired: false, publicationNote: "",
    registeredAgentRequired: true, filingOffice: "New Jersey Division of Revenue and Enterprise Services",
    filingUrl: "https://www.njconsumeraffairs.gov",
    einRequired: true, operatingAgreementRequired: false,
    operatingAgreementNote: "Recommended but not required",
    keyFacts: ["Fast online processing", "$75 annual report", "Online business registration portal"],
    warnings: ["High income tax rates up to 10.75%"]
  },
  NM: {
    name: "New Mexico", abbr: "NM", filingFee: 50, processingTime: "1–2 business days (online)",
    expeditedFee: null, expeditedTime: null,
    annualReportFee: 0, annualReportDue: "No annual report required",
    stateTax: "1.7%–5.9%", franchiseTax: null, franchiseTaxNote: "",
    namingRequirements: ["Must include 'LLC', 'L.L.C.', or 'Limited Liability Company'"],
    publicationRequired: false, publicationNote: "",
    registeredAgentRequired: false, filingOffice: "New Mexico Secretary of State",
    filingUrl: "https://www.sos.nm.gov/business-services",
    einRequired: true, operatingAgreementRequired: false,
    operatingAgreementNote: "Recommended but not required",
    keyFacts: ["Only state that does NOT require a registered agent", "No annual report required", "Low $50 formation fee", "Members not listed in public filings — strong privacy"],
    warnings: []
  },
  NY: {
    name: "New York", abbr: "NY", filingFee: 200, processingTime: "7 business days",
    expeditedFee: 25, expeditedTime: "24 hours",
    annualReportFee: 9, annualReportDue: "Biennial Statement, $9, every 2 years",
    stateTax: "4%–10.9%", franchiseTax: null, franchiseTaxNote: "",
    namingRequirements: ["Must include 'LLC', 'L.L.C.', 'Limited Liability Company', or 'Limited Liability Co.'"],
    publicationRequired: true, publicationNote: "REQUIRED: Must publish Articles of Organization in 2 designated newspapers for 6 consecutive weeks. Cost: $400–$2,000+ in NYC. MUST file Certificate of Publication within 120 days or LLC is suspended.",
    registeredAgentRequired: true, filingOffice: "New York Department of State",
    filingUrl: "https://www.dos.ny.gov/corps/llcguide.html",
    einRequired: true, operatingAgreementRequired: true,
    operatingAgreementNote: "New York LLC Law Section 417 REQUIRES a written operating agreement",
    keyFacts: ["Operating Agreement is LEGALLY REQUIRED in New York", "Publications in NYC can cost $1,500–$2,000+", "Upstate NY publications are much cheaper ($50–$200)", "$9 biennial statement (very low ongoing cost)"],
    warnings: ["PUBLICATION REQUIRED — mandatory and expensive, especially in NYC ($400–$2,000+)", "OPERATING AGREEMENT REQUIRED by law — not just recommended", "Must complete publication within 120 days or LLC authority is suspended"]
  },
  NC: {
    name: "North Carolina", abbr: "NC", filingFee: 125, processingTime: "7–10 business days",
    expeditedFee: 200, expeditedTime: "Same day",
    annualReportFee: 202, annualReportDue: "Annual Report, $202, by April 15",
    stateTax: "4.5% flat (decreasing)", franchiseTax: null, franchiseTaxNote: "",
    namingRequirements: ["Must include 'LLC', 'L.L.C.', or 'Limited Liability Company'"],
    publicationRequired: false, publicationNote: "",
    registeredAgentRequired: true, filingOffice: "North Carolina Secretary of State",
    filingUrl: "https://www.sosnc.gov/online_services/search/by_title/_Business_Registration",
    einRequired: true, operatingAgreementRequired: false,
    operatingAgreementNote: "Recommended but not required",
    keyFacts: ["Flat income tax rate decreasing to 3.99% by 2026", "Online filing available"],
    warnings: ["$202 annual report fee is on the higher end"]
  },
  ND: {
    name: "North Dakota", abbr: "ND", filingFee: 135, processingTime: "3–5 business days",
    expeditedFee: null, expeditedTime: null,
    annualReportFee: 50, annualReportDue: "Annual Report, $50, by November 15",
    stateTax: "1.95%–2.5% flat", franchiseTax: null, franchiseTaxNote: "",
    namingRequirements: ["Must include 'LLC', 'L.L.C.', or 'Limited Liability Company'"],
    publicationRequired: false, publicationNote: "",
    registeredAgentRequired: true, filingOffice: "North Dakota Secretary of State",
    filingUrl: "https://www.sos.nd.gov/business/business-services",
    einRequired: true, operatingAgreementRequired: false,
    operatingAgreementNote: "Recommended but not required",
    keyFacts: ["Very low income tax (1.95–2.5%)", "Online filing available"],
    warnings: []
  },
  OH: {
    name: "Ohio", abbr: "OH", filingFee: 99, processingTime: "3–5 business days",
    expeditedFee: null, expeditedTime: null,
    annualReportFee: 0, annualReportDue: "No annual report required",
    stateTax: "0%–3.5% (low income brackets exempt)", franchiseTax: null, franchiseTaxNote: "",
    namingRequirements: ["Must include 'LLC', 'L.L.C.', or 'Limited Liability Company'"],
    publicationRequired: false, publicationNote: "",
    registeredAgentRequired: true, filingOffice: "Ohio Secretary of State",
    filingUrl: "https://www.ohiosos.gov/businesses",
    einRequired: true, operatingAgreementRequired: false,
    operatingAgreementNote: "Recommended but not required",
    keyFacts: ["No annual report required", "Low income tax with zero bracket for low earners", "Online filing available"],
    warnings: []
  },
  OK: {
    name: "Oklahoma", abbr: "OK", filingFee: 100, processingTime: "3–5 business days",
    expeditedFee: null, expeditedTime: null,
    annualReportFee: 25, annualReportDue: "Annual Certificate, $25, by anniversary",
    stateTax: "0.25%–4.75%", franchiseTax: null, franchiseTaxNote: "",
    namingRequirements: ["Must include 'LLC', 'L.L.C.', or 'Limited Liability Company'"],
    publicationRequired: false, publicationNote: "",
    registeredAgentRequired: true, filingOffice: "Oklahoma Secretary of State",
    filingUrl: "https://www.sos.ok.gov/business",
    einRequired: true, operatingAgreementRequired: false,
    operatingAgreementNote: "Recommended but not required",
    keyFacts: ["Low $25 annual certificate fee", "Online filing available"],
    warnings: []
  },
  OR: {
    name: "Oregon", abbr: "OR", filingFee: 100, processingTime: "1–2 business days (online)",
    expeditedFee: null, expeditedTime: null,
    annualReportFee: 100, annualReportDue: "Annual Report, $100, by anniversary",
    stateTax: "4.75%–9.9%", franchiseTax: null, franchiseTaxNote: "",
    namingRequirements: ["Must include 'LLC', 'L.L.C.', or 'Limited Liability Company'"],
    publicationRequired: false, publicationNote: "",
    registeredAgentRequired: true, filingOffice: "Oregon Secretary of State",
    filingUrl: "https://sos.oregon.gov/business/Pages/register.aspx",
    einRequired: true, operatingAgreementRequired: false,
    operatingAgreementNote: "Recommended but not required",
    keyFacts: ["No sales tax", "Fast online processing", "Annual report $100"],
    warnings: ["High income tax rates up to 9.9%"]
  },
  PA: {
    name: "Pennsylvania", abbr: "PA", filingFee: 125, processingTime: "7–10 business days",
    expeditedFee: null, expeditedTime: null,
    annualReportFee: 7, annualReportDue: "Annual Report, $7",
    stateTax: "3.07% flat", franchiseTax: null, franchiseTaxNote: "",
    namingRequirements: ["Must include 'LLC', 'L.L.C.', or 'Limited Liability Company'"],
    publicationRequired: false, publicationNote: "",
    registeredAgentRequired: true, filingOffice: "Pennsylvania Department of State",
    filingUrl: "https://www.dos.pa.gov/BusinessCharities/Business",
    einRequired: true, operatingAgreementRequired: false,
    operatingAgreementNote: "Recommended but not required",
    keyFacts: ["Very low $7 annual report fee", "3.07% flat income tax (low)", "Online filing available"],
    warnings: []
  },
  RI: {
    name: "Rhode Island", abbr: "RI", filingFee: 150, processingTime: "5–7 business days",
    expeditedFee: null, expeditedTime: null,
    annualReportFee: 50, annualReportDue: "Annual Report, $50, by November 1",
    stateTax: "3.75%–5.99%", franchiseTax: null, franchiseTaxNote: "",
    namingRequirements: ["Must include 'LLC', 'L.L.C.', or 'Limited Liability Company'"],
    publicationRequired: false, publicationNote: "",
    registeredAgentRequired: true, filingOffice: "Rhode Island Secretary of State",
    filingUrl: "https://www.sos.ri.gov/divisions/business-services",
    einRequired: true, operatingAgreementRequired: false,
    operatingAgreementNote: "Recommended but not required",
    keyFacts: ["Online filing available", "$50 annual report"],
    warnings: []
  },
  SC: {
    name: "South Carolina", abbr: "SC", filingFee: 110, processingTime: "3–5 business days",
    expeditedFee: null, expeditedTime: null,
    annualReportFee: 0, annualReportDue: "No annual report required",
    stateTax: "3%–6.4%", franchiseTax: null, franchiseTaxNote: "",
    namingRequirements: ["Must include 'LLC', 'L.L.C.', or 'Limited Liability Company'"],
    publicationRequired: false, publicationNote: "",
    registeredAgentRequired: true, filingOffice: "South Carolina Secretary of State",
    filingUrl: "https://businessfilings.sc.gov",
    einRequired: true, operatingAgreementRequired: false,
    operatingAgreementNote: "Recommended but not required",
    keyFacts: ["No annual report required", "Online filing available"],
    warnings: []
  },
  SD: {
    name: "South Dakota", abbr: "SD", filingFee: 150, processingTime: "3–5 business days",
    expeditedFee: null, expeditedTime: null,
    annualReportFee: 50, annualReportDue: "Annual Report, $50, by first day of anniversary month",
    stateTax: "No state income tax", franchiseTax: null, franchiseTaxNote: "",
    namingRequirements: ["Must include 'LLC', 'L.L.C.', or 'Limited Liability Company'"],
    publicationRequired: false, publicationNote: "",
    registeredAgentRequired: true, filingOffice: "South Dakota Secretary of State",
    filingUrl: "https://sdsos.gov/business-services",
    einRequired: true, operatingAgreementRequired: false,
    operatingAgreementNote: "Recommended but not required",
    keyFacts: ["No state income tax", "No corporate income tax", "Online filing available"],
    warnings: []
  },
  TN: {
    name: "Tennessee", abbr: "TN", filingFee: 300, processingTime: "3–5 business days",
    expeditedFee: null, expeditedTime: null,
    annualReportFee: 300, annualReportDue: "Annual Report, minimum $300, by April 1",
    stateTax: "No income tax on wages", franchiseTax: null, franchiseTaxNote: "",
    namingRequirements: ["Must include 'LLC', 'L.L.C.', or 'Limited Liability Company'"],
    publicationRequired: false, publicationNote: "",
    registeredAgentRequired: true, filingOffice: "Tennessee Secretary of State",
    filingUrl: "https://sos.tn.gov/businesses",
    einRequired: true, operatingAgreementRequired: false,
    operatingAgreementNote: "Recommended but not required",
    keyFacts: ["No income tax on wages", "Business and excise taxes apply to business income"],
    warnings: ["$300 formation fee AND $300 minimum annual report — expensive", "Franchise & Excise Tax applies to business income even if no personal income tax"]
  },
  TX: {
    name: "Texas", abbr: "TX", filingFee: 300, processingTime: "3–5 business days",
    expeditedFee: null, expeditedTime: null,
    annualReportFee: 0, annualReportDue: "Public Information Report (PIR), no fee, due May 15",
    stateTax: "No state income tax", franchiseTax: null, franchiseTaxNote: "Texas Franchise Tax: 0.375% for wholesalers/retailers, 0.75% for others — exempt if revenue < $2.47M",
    namingRequirements: ["Must include 'LLC', 'L.L.C.', 'Limited Liability Company', or 'Limited Liability Co.'", "Cannot include 'Lotto' or 'Lottery'"],
    publicationRequired: false, publicationNote: "",
    registeredAgentRequired: true, filingOffice: "Texas Secretary of State",
    filingUrl: "https://www.sos.state.tx.us/corp/forms_boc.shtml",
    einRequired: true, operatingAgreementRequired: false,
    operatingAgreementNote: "Not required but strongly recommended — Texas Business Organizations Code is flexible",
    keyFacts: ["No personal income tax", "Free Public Information Report (no filing fee)", "Franchise Tax exempt for most small LLCs under $2.47M revenue"],
    warnings: ["$300 formation fee is on the higher end", "Franchise Tax applies to larger businesses — calculate before forming"]
  },
  UT: {
    name: "Utah", abbr: "UT", filingFee: 54, processingTime: "1–2 business days (online)",
    expeditedFee: null, expeditedTime: null,
    annualReportFee: 18, annualReportDue: "Annual Renewal, $18, by anniversary",
    stateTax: "4.65% flat", franchiseTax: null, franchiseTaxNote: "",
    namingRequirements: ["Must include 'LLC', 'L.L.C.', or 'Limited Liability Company'"],
    publicationRequired: false, publicationNote: "",
    registeredAgentRequired: true, filingOffice: "Utah Division of Corporations",
    filingUrl: "https://corporations.utah.gov",
    einRequired: true, operatingAgreementRequired: false,
    operatingAgreementNote: "Recommended but not required",
    keyFacts: ["Fast online processing", "Very low $18 annual renewal", "4.65% flat income tax"],
    warnings: []
  },
  VT: {
    name: "Vermont", abbr: "VT", filingFee: 125, processingTime: "5–7 business days",
    expeditedFee: null, expeditedTime: null,
    annualReportFee: 35, annualReportDue: "Annual Report, $35, by March 15",
    stateTax: "3.35%–8.75%", franchiseTax: null, franchiseTaxNote: "",
    namingRequirements: ["Must include 'LLC', 'L.L.C.', or 'Limited Liability Company'"],
    publicationRequired: false, publicationNote: "",
    registeredAgentRequired: true, filingOffice: "Vermont Secretary of State",
    filingUrl: "https://sos.vermont.gov/corporations",
    einRequired: true, operatingAgreementRequired: false,
    operatingAgreementNote: "Recommended but not required",
    keyFacts: ["Online filing available", "$35 annual report"],
    warnings: []
  },
  VA: {
    name: "Virginia", abbr: "VA", filingFee: 100, processingTime: "1–2 business days (online)",
    expeditedFee: null, expeditedTime: null,
    annualReportFee: 50, annualReportDue: "Annual Registration Fee, $50, by anniversary month",
    stateTax: "2%–5.75%", franchiseTax: null, franchiseTaxNote: "",
    namingRequirements: ["Must include 'LLC', 'L.L.C.', or 'Limited Liability Company'"],
    publicationRequired: false, publicationNote: "",
    registeredAgentRequired: true, filingOffice: "Virginia State Corporation Commission",
    filingUrl: "https://www.scc.virginia.gov/pages/LLC-Information",
    einRequired: true, operatingAgreementRequired: false,
    operatingAgreementNote: "Recommended but not required",
    keyFacts: ["Fast online processing", "$50 annual registration fee", "Online filing via Clerk's Information System (CIS)"],
    warnings: []
  },
  WA: {
    name: "Washington", abbr: "WA", filingFee: 230, processingTime: "3–5 business days",
    expeditedFee: null, expeditedTime: null,
    annualReportFee: 71, annualReportDue: "Annual Report, $71, by anniversary",
    stateTax: "No state income tax", franchiseTax: null, franchiseTaxNote: "Business & Occupation (B&O) tax: 0.15%–1.5% of gross receipts (varies by industry)",
    namingRequirements: ["Must include 'LLC', 'L.L.C.', or 'Limited Liability Company'"],
    publicationRequired: false, publicationNote: "",
    registeredAgentRequired: true, filingOffice: "Washington Secretary of State",
    filingUrl: "https://www.sos.wa.gov/corps",
    einRequired: true, operatingAgreementRequired: false,
    operatingAgreementNote: "Recommended but not required",
    keyFacts: ["No personal income tax", "B&O tax applies on gross revenue (not profit)", "Online filing via Washington Corporations & Charities Filing System"],
    warnings: ["B&O tax applies to gross revenue — factor this into pricing", "Capital gains tax applies to high earners"]
  },
  WV: {
    name: "West Virginia", abbr: "WV", filingFee: 100, processingTime: "3–5 business days",
    expeditedFee: null, expeditedTime: null,
    annualReportFee: 25, annualReportDue: "Annual Report, $25",
    stateTax: "3%–6.5%", franchiseTax: null, franchiseTaxNote: "",
    namingRequirements: ["Must include 'LLC', 'L.L.C.', or 'Limited Liability Company'"],
    publicationRequired: false, publicationNote: "",
    registeredAgentRequired: true, filingOffice: "West Virginia Secretary of State",
    filingUrl: "https://sos.wv.gov/business/Pages/default.aspx",
    einRequired: true, operatingAgreementRequired: false,
    operatingAgreementNote: "Recommended but not required",
    keyFacts: ["Low $25 annual report", "Online filing available"],
    warnings: []
  },
  WI: {
    name: "Wisconsin", abbr: "WI", filingFee: 130, processingTime: "5–7 business days",
    expeditedFee: null, expeditedTime: null,
    annualReportFee: 25, annualReportDue: "Annual Report, $25, by end of quarter of anniversary month",
    stateTax: "3.54%–7.65%", franchiseTax: null, franchiseTaxNote: "",
    namingRequirements: ["Must include 'LLC', 'L.L.C.', or 'Limited Liability Company'"],
    publicationRequired: false, publicationNote: "",
    registeredAgentRequired: true, filingOffice: "Wisconsin Department of Financial Institutions",
    filingUrl: "https://www.wdfi.org/corporations/llc",
    einRequired: true, operatingAgreementRequired: false,
    operatingAgreementNote: "Recommended but not required",
    keyFacts: ["Low $25 annual report fee", "Online filing available"],
    warnings: []
  },
  WY: {
    name: "Wyoming", abbr: "WY", filingFee: 100, processingTime: "1–2 business days (online)",
    expeditedFee: null, expeditedTime: null,
    annualReportFee: 60, annualReportDue: "Annual Report, minimum $60, by first day of anniversary month",
    stateTax: "No state income tax", franchiseTax: null, franchiseTaxNote: "",
    namingRequirements: ["Must include 'LLC', 'L.L.C.', or 'Limited Liability Company'"],
    publicationRequired: false, publicationNote: "",
    registeredAgentRequired: true, filingOffice: "Wyoming Secretary of State",
    filingUrl: "https://sos.wyo.gov/business/startabusiness.aspx",
    einRequired: true, operatingAgreementRequired: false,
    operatingAgreementNote: "Recommended but not required",
    keyFacts: ["No state income tax", "No franchise tax", "Excellent asset protection laws", "Strong privacy — members not publicly listed", "One of the best states for LLC formation"],
    warnings: ["$60 minimum annual report (based on assets in Wyoming)", "Popular for out-of-state LLCs but you'll still need to foreign qualify in your home state"]
  },
  DC: {
    name: "Washington D.C.", abbr: "DC", filingFee: 220, processingTime: "5–7 business days",
    expeditedFee: null, expeditedTime: null,
    annualReportFee: 300, annualReportDue: "Biennial Report, $300, every 2 years",
    stateTax: "4%–10.75%", franchiseTax: null, franchiseTaxNote: "",
    namingRequirements: ["Must include 'LLC', 'L.L.C.', or 'Limited Liability Company'"],
    publicationRequired: false, publicationNote: "",
    registeredAgentRequired: true, filingOffice: "DC Department of Licensing and Consumer Protection",
    filingUrl: "https://business.dc.gov",
    einRequired: true, operatingAgreementRequired: false,
    operatingAgreementNote: "Recommended but not required",
    keyFacts: ["Online filing via DC Integrated Portal", "$300 biennial report fee"],
    warnings: ["$300 biennial report fee is high", "High income tax rates up to 10.75%"]
  }
};

export const NO_INCOME_TAX_STATES = ["AK", "FL", "NV", "NH", "SD", "TN", "TX", "WA", "WY"];
export const PUBLICATION_REQUIRED = ["AZ", "NE", "NY"];
export const LOWEST_FEE_STATES = ["MT", "KY", "AZ", "MI", "MS", "MO", "IA"].sort();

export function getStateData(abbr: string): StateData | undefined {
  return LLC_STATES[abbr.toUpperCase()];
}

export function getAllStates(): StateData[] {
  return Object.values(LLC_STATES).sort((a, b) => a.name.localeCompare(b.name));
}
